apiVersion: batch/v1
kind: Job
metadata:
  name: fm-benchmark-job
  namespace: braingeneers
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: jzhu647/fm_benchmark:latest
        imagePullPolicy: Always
        command: ["python3", "main_benchmark.py"]
        args: [
          "--test_dir", "test_data",
          "--ref_annot", "prediction_obs.tsv",
          "--obo", "cl.obo",
          "--s3_bucket", "latentbrain",
          "--s3_prefix", "combined_UCE_5neuro/"
        ]
        resources:
          requests:
            memory: "32Gi"
            cpu: "2"
          limits:
            memory: "64Gi"
            cpu: "4"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: latentbrain-aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: latentbrain-aws-creds
              key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: arm64
